### ISSUE TITLE
Unable to open shell due to `ShellDetectionFailure` on ARM architecture

### ISSUE THREAD

**Issue by ltalirz** [aiidalab/aiidalab-docker-stack#202]
```
$ docker exec --user aiida -it aiidalab bash
Could not open a connection to your authentication agent.
Traceback (most recent call last):
  File "/opt/conda/bin/verdi", line 8, in <module>
    sys.exit(verdi())
  File "/opt/conda/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/click/core.py", line 777, in main
    _bashcomplete(self, prog_name, complete_var)
  File "/opt/conda/lib/python3.7/site-packages/click_completion/patch.py", line 122, in _shellcomplete
    echo(get_code(prog_name=prog_name, env_name=complete_var))
  File "/opt/conda/lib/python3.7/site-packages/click_completion/core.py", line 299, in get_code
    shell = get_auto_shell()
  File "/opt/conda/lib/python3.7/site-packages/click_completion/lib.py", line 125, in get_auto_shell
    return shellingham.detect_shell()[0]
  File "/opt/conda/lib/python3.7/site-packages/shellingham/__init__.py", line 24, in detect_shell
    raise ShellDetectionFailure()
shellingham._core.ShellDetectionFailure
```

Edit: I see from the python version that this must still be an old, patched version of the container. Will retry it with the new one  (but internet is too bad here)

**Comment by ltalirz** [comment]
@yakutovicha is it the same for you?

**Comment by yakutovicha** [comment]
> @yakutovicha is it the same for you?

no, I could enter the container without any problems.

**Comment by unkcpz** [comment]
I think the new container doesn't have this issue anymore. The Python version is now `3.9.13` and `aiida-core==2.3.1`. close.
